/*
  Runtime manifest for the optimized image variants generated by
  scripts/optimize-images.mjs into this directory.

  Variant files are discovered with import.meta.glob (URL strings only, so
  nothing is bundled into JavaScript). Lookup is keyed by the original file
  basename without extension, e.g. 'work-01-aureli-brand-identity'.

  Fallback <img> sources keep pointing at the untouched originals.
*/

const AVIF_URLS = import.meta.glob('./*.avif', {
  eager: true,
  import: 'default',
  query: '?url',
}) as Record<string, string>;

const WEBP_URLS = import.meta.glob('./*.webp', {
  eager: true,
  import: 'default',
  query: '?url',
}) as Record<string, string>;

/** Intrinsic dimensions of every optimized source image. */
const SOURCE_DIMENSIONS: Record<string, { width: number; height: number }> = {
  'taha-hero-background': { width: 1536, height: 1024 },
  'taha-card-01-brand-identity': { width: 1536, height: 1024 },
  'taha-card-02-packaging': { width: 1536, height: 1024 },
  'taha-card-03-editorial': { width: 1536, height: 1024 },
  'work-01-aureli-brand-identity': { width: 1536, height: 1024 },
  'work-02-noma-social-campaign': { width: 1536, height: 1024 },
  'work-03-vertex-packaging': { width: 1536, height: 1024 },
  'work-04-mono-editorial': { width: 1536, height: 1024 },
  'work-05-northline-website': { width: 1536, height: 1024 },
  'work-06-clarity-advertising': { width: 1536, height: 1024 },
  'service-01-brand-identity-hover': { width: 1448, height: 1086 },
  'service-02-social-media-hover': { width: 1416, height: 1111 },
  'service-03-advertising-hover': { width: 1413, height: 1113 },
  'service-04-packaging-hover': { width: 1414, height: 1113 },
  'service-05-website-ui-hover': { width: 1415, height: 1111 },
  'service-06-print-marketing-hover': { width: 1415, height: 1112 },
  taha: { width: 1122, height: 1402 },
  brand_mockup_1785252185476: { width: 1200, height: 896 },
  packaging_mockup_1785252204708: { width: 1200, height: 896 },
};

export interface OptimizedImage {
  /** Original file basename without extension. */
  key: string;
  /** Intrinsic dimensions of the source image. */
  width: number;
  height: number;
  /** Largest generated variant, used for hover preloading. */
  largestUrl: string;
  avifSrcSet: string;
  webpSrcSet: string;
}

const widthOf = (fileName: string): number => {
  const match = fileName.match(/-(\d+)\.(avif|webp)$/);
  return match ? Number(match[1]) : 0;
};

const buildSrcSet = (urls: Record<string, string>): string =>
  Object.entries(urls)
    .sort(([a], [b]) => widthOf(a) - widthOf(b))
    .map(([fileName, url]) => `${url} ${widthOf(fileName)}w`)
    .join(', ');

const keyOf = (fileName: string): string =>
  fileName.replace(/-\d+\.(avif|webp)$/, '');

const collect = (urls: Record<string, string>) => {
  const grouped = new Map<string, Record<string, string>>();
  for (const [fileName, url] of Object.entries(urls)) {
    const key = keyOf(fileName);
    const bucket = grouped.get(key) ?? {};
    bucket[fileName] = url;
    grouped.set(key, bucket);
  }
  return grouped;
};

const avifGrouped = collect(AVIF_URLS);
const webpGrouped = collect(WEBP_URLS);

export const optimizedImages: Record<string, OptimizedImage> = {};

for (const key of new Set([...avifGrouped.keys(), ...webpGrouped.keys()])) {
  const avif = avifGrouped.get(key);
  const webp = webpGrouped.get(key);
  if (!avif || !webp) continue;

  const dimensions = SOURCE_DIMENSIONS[key];
  if (!dimensions) continue;

  const largestEntry = Object.entries(avif).sort(
    ([a], [b]) => widthOf(b) - widthOf(a),
  )[0];

  optimizedImages[key] = {
    key,
    width: dimensions.width,
    height: dimensions.height,
    largestUrl: largestEntry[1],
    avifSrcSet: buildSrcSet(avif),
    webpSrcSet: buildSrcSet(webp),
  };
}

/**
 * Resolves a <img src> value (public path, imported Vite URL, remote URL)
 * to the optimized-variant record. Hashed Vite URLs match through their
 * original stem prefix, e.g. '/assets/brand_mockup_.....-xxxx.jpg'.
 */
export function getOptimizedImage(src: string): OptimizedImage | undefined {
  const basename = src.split('?')[0].split('/').pop() ?? '';
  const stem = basename.replace(/\.(png|jpe?g|webp|avif)$/i, '').toLowerCase();
  if (!stem) return undefined;
  const direct = optimizedImages[stem];
  if (direct) return direct;
  const byPrefix = Object.keys(optimizedImages).find(
    (key) => stem.length > key.length && stem.startsWith(`${key}-`),
  );
  return byPrefix ? optimizedImages[byPrefix] : undefined;
}